version: "3"

services:
    main:
        build: .
        restart: unless-stopped
        image: radarcz/radarsbutt-twitch
        ports:
            - 80:8081
            - 8080:8080
        stdin_open: true
        network_mode: bridge